### ISSUE TITLE
WaterQualityObserved

### ISSUE THREAD

**Issue by jordimartinezcat** [smart-data-models/dataModel.WaterQuality#13]
I’m trying to test the WaterQuality data model with Python code, and it’s returning a type error:

![image](https://github.com/smart-data-models/dataModel.WaterQuality/assets/131678670/8ab68315-7e3f-43ca-8f9d-adf6810de2f6)

Then I tried another model, such as datamodel.Weather/WeatherForecast, and the entity introduction was successful.
It seems that there is a difference between, for example, NO3 from dataModel.WaterQuality and precipitation from datamodel.Weather in the smartdatamodels.json file. Precipitation has a model attribute with the value “https://schema.org/Number,” but this attribute doesn’t exist for NO3 in the dataModel.WaterQuality.

If you need further information to reproduce the issue, feel free to ask!

Thank you

**Comment by albertoabellagarcia** [comment]
You are completely right, we have detected an issue in our program to generate the examples that we are fixing right now.

**Comment by jordimartinezcat** [comment]
Ok, thank you. 
Don’t hesitate to contact me if I can help with anything

**Comment by albertoabellagarcia** [comment]
Current version is tested. If you do not have installed a context broker in the environment running the program in port 1026 then the output will be : 

Variable matches the specified data type.
[False, "An error  type (HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /ngsi-ld/v1/entities (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bbd701f90>: Failed to establish a new connection: [Errno 111] Connection refused'))) occurred inserting the entity in broker :http://localhost:1026"]
Variable matches the specified data type.
[False, "An error  type (HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /ngsi-ld/v1/entities (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bbd82c3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))) occurred inserting the entity in broker :http://localhost:1026"]
Variable matches the specified data type.
[False, "An error  type (HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /ngsi-ld/v1/entities (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bab7ff4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))) occurred inserting the entity in broker :http://localhost:1026"]
Variable matches the specified data type.
[False, "An error  type (HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /ngsi-ld/v1/entities (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bbd8bdbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))) occurred inserting the entity in broker :http://localhost:1026"]
 In case you have installed the a cntext broker (see comments below )
 Execute this instruction to check that the entities has been inserted


Process finished with exit code 0

which is what is expected

Thank you for the feedback
